name: ib_base_env
channels:
- conda-forge
dependencies:
- python==3.6.3
- pyopencl
- pip:
    - Cython==0.27.3
    - numpy==1.13.3
    - progressbar2
    - scipy
    - setuptools
    - matplotlib
    - panda
    - pandas
