name: ib_base-environment
channels:
- conda-forge
dependencies:
- python-3.6
- pyopencl
- pip:
    - Cython                    
    - numpy                     
    - progressbar2              
    - scipy                     
    - setuptools
    - matplotlib
