name: ib_base-environment
channels:
appdirs                   1.4.3                     <pip>
argparse                  1.4.0                     <pip>
attrs                     17.4.0                    <pip>
certifi                   2017.11.5        py36hb8ac631_0  
cffi                      1.11.2                    <pip>
colorama                  0.3.9                     <pip>
cycler                    0.10.0                    <pip>
Cython                    0.27.3                    <pip>
dateutils                 0.6.6                     <pip>
decorator                 4.1.2                     <pip>
gmpy2                     2.0.8            py36h0300f35_2  
icc_rt                    2017.0.4             h97af966_0  
intel-openmp              2018.0.0             hd92c6cd_8  
Jinja2                    2.10                      <pip>
lpdec                     2015.1                    <pip>
Mako                      1.0.7                     <pip>
MarkupSafe                1.0                       <pip>
matplotlib                2.1.1                     <pip>
matplotlib2tikz           0.6.15                    <pip>
mkl                       2018.0.1             h2108138_4  
mpc                       1.0.3                h0ca6028_5  
mpfr                      3.1.5                h35fb66f_2  
mpir                      3.0.0                hec2e145_1  
mpmath                    1.0.0                     <pip>
numpy                     1.13.3                    <pip>
numpy                     1.13.3           py36ha320f96_0  
parse                     1.6.5                     <pip>
Pillow                    5.0.0                     <pip>
pip                       9.0.1            py36h226ae91_4  
pluggy                    0.6.0                     <pip>
progressbar2              3.34.3                    <pip>
py                        1.5.2                     <pip>
pycparser                 2.18                      <pip>
pyopencl                  2017.2.2+cl12             <pip>
pyparser                  1.0                       <pip>
pyparsing                 2.2.0                     <pip>
pytest                    3.3.1                     <pip>
python                    3.6.3                h3b118a2_4  
python-dateutil           2.6.1                     <pip>
python-utils              2.2.0                     <pip>
pytools                   2017.6                    <pip>
pytz                      2017.3                    <pip>
scipy                     1.0.0            py36h1260518_0  
setuptools                36.5.0           py36h65f9e6e_0  
simplejson                3.13.2                    <pip>
six                       1.11.0                    <pip>
SQLAlchemy                1.2.0                     <pip>
sympy                     1.1.1                     <pip>
vc                        14                   h2379b0c_2  
vs2015_runtime            14.0.25123           hd4c4e62_2  
wheel                     0.30.0           py36h6c3ec14_1  
wincertstore              0.2              py36h7fe50ca_0  
