name: ib_base-environment
channels:
- conda-forge
dependencies:
- Cython                    
- numpy                     
- python                    
- progressbar2              
- scipy                     
- setuptools                
